= clj-kafka-x

A Clojure library for the Apache Kafka (distributed stream-processing software platform). 

Uses KF protocol and not rely on ZooKeeper. 

NOTE: v0.4.0 version is well tested with Kafka v2.2.x and 2.3.0 with native drivers on Scala 2.11 and 2.12. Still contains zookeeper as a dependency.

Tries to be as lightweigh as possible thus depends only on 

- `org.apache.kafka/kafka_2.12 "2.3.0"`
- `org.apache.kafka/kafka-clients "2.3.0"`
- `org.apache.zookeeper/zookeeper "3.5.5"`

but excluding `jms`,`jmx*` and logging.

CAUTION: `v0.4.0` may be partially (or even fully!) incompatible with some versions of other libraries that use NIO!

Current version is:

image:https://img.shields.io/clojars/v/net.tbt-post/clj-kafka-x.svg[]

== Installation

Add the following to your http://github.com/technomancy/leiningen[Leiningen's]
`project.clj`:

[source,clojure]
----
[net.tbt-post/clj-kafka-x "0.3.1"]
----

== Usage

=== Producer

[source,clojure]
----
(require '[clj-kafka-x.producer :as kp])

(with-open [p (kp/producer {"bootstrap.servers" "localhost:9092"}
                           (kp/string-serializer)
                           (kp/string-serializer))]
  @(kp/send p (kp/record "topic-a" "Hi there!")))
----

=== Consumer

[source,clojure]
----
(require '[clj-kafka-x.consumers.simple :as kc])

(with-open [c (kc/consumer {"bootstrap.servers" "localhost:9092"
                            "group.id" "consumer-id"}
                            (kc/string-deserializer)
                            (kc/string-deserializer))]
  (kc/subscribe c "topic-a")
  (kc/messages c))
----

NOTE: When you use multiple partitions per topic it is required
to specify them explicitly when subscribing, i.e.
`(kc/subscribe
    c [{:topic "topic-a" :partitions #{0 1}}
       {:topic "topic-b" :partitions #{0 1 2}}])`

.Real-life (almost) example
[source,clojure]
----
(ns buzz.consumer.kafka
  (:require [clj-kafka-x.consumers.simple :as kc]
            [clojure.tools.logging :as log]))

(defn processor [msg schema] msg)
(def schema nil)
(def config {"bootstrap.servers" "localhost:9092"
             "group.id" "consumer-id"})

(defn process-message [msg]
  (let [{:keys [value topic partition offset]} msg
        processor processor ;; choose one by topic name
        schema schema]      ;; choose one by topic name
    (if (fn? processor) (processor value schema) value)))

(defn consume []
  (with-open [c (kc/consumer config
                             (kc/byte-array-deserializer)
                             (kc/byte-array-deserializer))]
    (kc/subscribe c (config/kafka-topics))
    (let [pool (kc/messages c)]
      (doseq [message pool]
        (log/warn (process-message message))))))
----

== Manual Build

[source,text]
----
$ lein install
----

== License

Copyright © 2016-2019

Distributed under the
http://www.apache.org/licenses/LICENSE-2.0[Apache License v 2.0]

